### ISSUE TITLE
Search range question.

### ISSUE THREAD

**Issue by btctalkdoitnow** [JeanLucPons/VanitySearch#44]
I know this program searches for 256 bit keys. I took a look at the code and I suppose it searches 255,254.. bit too. Is it true? Any comments, please.

**Comment by ZielarSRC** [comment]
> Thanks for this amazing program. I know this program searching for 256 bit keys. I took a look at the code and I suppose it is searching 255,254.. bit too. Is it true? Any comments, please.

Practically you are right, but theoretically you are not.
VanitySearch is programmed to search for prefixes in random locations, so the author did not create this solution and probably does not plan, because he is not involved (not my cause for what) in the development of the project.
I have a modified version of VanitySearch that makes it possible, but even if it is not for technical reasons (there is no certainty that it works 100% correctly) then it is for my own use and I do not intend to sell it (I am not the author of this version).

**Comment by btctalkdoitnow** [comment]
I just want to VS starting points is only 256bit, not 255,254 and so on. I hope it is possible to patch it without performance lose.
